name: Build Mod

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Clears the Node deprecation error

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android64
            os: windows-2022 # Forces the runner to a highly stable Windows environment
            target: Android64
          - name: Android32
            os: windows-2022
            target: Android32

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          ccache-variant: "" # Bypasses the caching path validation failure completely
